version: '3'

services:
  mydb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mydb
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: ${DBNAME}
       MYSQL_ROOT_PASSWORD: ${RPASSWORD}
    networks:
      - docker_network
    restart: always

  web:
    build: .
    command: bash -c "python manage.py makemigrations --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    env_file:
    -  ../.env
    container_name: dj
    volumes:
      - ./:/mynote
    expose:
      - '80'
    depends_on:
      - mydb
    networks:
      - docker_network

  ngx:
    image: nginx:latest
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d
      - ./config/static/:/static
    depends_on:
      - web
    networks:
      - docker_network
    
networks:
  docker_network:
    driver: bridge
